version: "3.8"

services:
  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring_network

  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - monitoring_network

volumes:
  grafana_storage:
    driver: local

networks:
  monitoring_network:
    driver: bridge
