{
 "title": "MedIoT Analytics",
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate – All Services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (path) (rate(http_requests_total[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Ingestion Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(vital_ingestion_latency_seconds_bucket[5m])"
    }
   ]
  },
  {
   "title": "Live Patient Vital Values",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "patient_vital_value",
     "legendFormat": "{{patient_id}} - {{sensor_type}}"
    }
   ]
  },
  {
   "title": "Alert Volume Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{path=\"/api/v1/alerts\"}[5m]))",
     "legendFormat": "Alerts"
    }
   ]
  }
 ]
}